# Generated by Django 4.1.2 on 2022-11-04 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descriptions', models.TextField()),
                ('publish', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
