# Generated by Django 4.1.3 on 2023-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'publish'), ('i', 'pendeing'), ('b', 'back')], max_length=1),
        ),
    ]
