# Generated by Django 4.1.2 on 2022-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'publish')], max_length=1),
        ),
    ]
